# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Kaike-Zhang"
repo_name: "Robust_arXiv_daily"
show_authors: True
show_links: True
show_badge: True
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/rs-arxiv-daily.json'
json_gitpage_path: './docs/rs-arxiv-daily-web.json'
json_wechat_path: './docs/rs-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "RobustnessRS": 
        filters: ['("Robust" OR "Robustness" OR "Defense") AND (ti:"Recommender System" OR ti:"Collaborative Filtering")']
    "Robust ML":
        filters: ['(ti:"Robust" OR ti:"Robustness") AND (ti:"Adversarial" OR ti:"Certifiable") OR ti:"Machine Learning"']
    "Security LLM":
        filters: ['(ti:"Robust" OR ti:"Robustness") AND (ti:"GPT" OR ti:"LLM" OR ti:"Large Language Model")']
